name: Test, Build and Publish
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: npm run typecheck
    - run: npm test
    - run: npm run build
    - run: npm run coverage
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: Pikaso Bundles
        path: |
          lib
          esm
    - uses: coverallsapp/github-action@master
      with:
        name: Coveralls
        github-token: ${{ secrets.GITHUB_TOKEN }}